# Generated by Django 5.0.2 on 2024-04-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, help_text='First name of the user.', max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, help_text='Last name of the user.', max_length=255, null=True)),
                ('email', models.EmailField(db_index=True, max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
