# Generated by Django 5.0.2 on 2024-04-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermaster',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the user is active.'),
        ),
        migrations.AddField(
            model_name='usermaster',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Whether the user is an admin.'),
        ),
        migrations.AddField(
            model_name='usermaster',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Whether the user is a staff member.'),
        ),
        migrations.AddField(
            model_name='usermaster',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Whether the user is a superuser.'),
        ),
    ]
